plugins {
    id 'application'
    // Plugin for generating Java source files from Protocol Buffers (.proto) files.
    id("com.google.protobuf") version "0.9.6"
}

repositories {
    mavenCentral()
}

def grpcVersion = '1.80.0'
def protobufVersion = '4.34.1'

dependencies {
    // https://mvnrepository.com/artifact/com.google.protobuf/protobuf-java-util
    implementation "com.google.protobuf:protobuf-java-util:${protobufVersion}"
    // https://mvnrepository.com/artifact/io.grpc/grpc-protobuf
    implementation "io.grpc:grpc-protobuf:${grpcVersion}"
    // https://mvnrepository.com/artifact/io.grpc/grpc-stub
    implementation "io.grpc:grpc-stub:${grpcVersion}"
    // https://mvnrepository.com/artifact/io.grpc/grpc-netty-shaded
    runtimeOnly "io.grpc:grpc-netty-shaded:${grpcVersion}"
    
    // Dependências do JUnit 5
    testImplementation 'org.junit.jupiter:junit-jupiter:5.12.2' //**** */
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'//***** */

    
    // manter as demais dependências do projeto que foram criadas pelo assistente do Gradle
}

// Configuração do plugin protobuf
protobuf {
    // Baixar o protoc deste repositório
    protoc {
        artifact = "com.google.protobuf:protoc:${protobufVersion}"
    }
    // Compilador gRPC para java
    plugins {
        grpc {
            artifact = "io.grpc:protoc-gen-grpc-java:${grpcVersion}"
        }
    }
    // Configuração da tarefa para o compilador gRPC (saída padrão é Java)
    generateProtoTasks {
    all()*.plugins { grpc {} }
    }
}

// Para indicar para as IDEs onde estão as classes geradas a partir do arquivo .proto
sourceSets {
    main {
        java {
            srcDirs 'build/generated/source/proto/main/grpc'
            srcDirs 'build/generated/source/proto/main/java'
        }
    }
}

application {
    // Define the main class for the application.
    mainClass = 'engtelecom.std.App'
}

tasks.named('test') {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}