/*
 * This source file was generated by the Gradle 'init' task
 */
package engtelecom.std;
import module java.base; // apenas para JAVA 25. Tem varias bibliotecas/classes

public class App {

    public static void main(String[] args) {

        int porta  = 1234;
        System.out.println("..:: Servidor ::..");

        // assumindo que o clientSocket já foi criado previamente
        try (ServerSocket serverSocket = new ServerSocket(porta)) {

            System.out.println("Aguardando por conexões...");
            var clientSocket = serverSocket.accept();
            Thread.ofVirtual().start(new AtenderCliente(clientSocket));

        }catch(Exception e){
            System.err.println("Erro: " + e);
        }

    }

}
