/*
 * This source file was generated by the Gradle 'init' task
 */

// ./gradlew installDist -q --console=plain
// ./app/build/install/app/bin/app

package engtelecom.std;

import module java.base;

public class App {

    public static void main(String[] args) {

        int porta = 1234;
        String host = "localhost";

        if(args.length == 2){
            host = args[0];
            porta = Integer.parseInt(args[1]);
        }

        try(
                var socket = new Socket(host, porta);
                var reader = new BufferedReader(
                        new InputStreamReader(socket.getInputStream(), StandardCharsets.UTF_8)
                ); // input

                var writer = new BufferedWriter(
                        new OutputStreamWriter(socket.getOutputStream(), StandardCharsets.UTF_8)
                ); // output
        ){

            System.out.println("Conectado no servidor...");
            // Protocolo de comunicação
            // 1- Cliente envia a mensagem ao servidor
            String mensagem = " ";
            String resposta = " ";
            do{

                mensagem = IO.readln("Entre com a mensagem: ");
                writer.write(mensagem);
                writer.newLine();
                writer.flush();

                // 2- Resposta do servidor
                resposta = reader.readLine();
                System.out.printf("Resposta do servidor: %s%n", resposta);

            }while(!(mensagem.equalsIgnoreCase("sair")));

            System.out.println("Cliente finalizado!");
        }catch(Exception e){
            System.err.println("erro: " + e);
        }

    }
}