/*
 * This source file was generated by the Gradle 'init' task
 */

// ./gradlew installDist -q --console=plain
// ./app/build/install/app/bin/app

package engtelecom.std;

import module java.base; // apenas para JAVA 25. Tem varias bibliotecas/classes

public class App {

    public static void main(String[] args) {

        int porta  = 1234;
        System.out.println("..:: Servidor ::..");

        // é obrigatório tratar exceção de a porta estar sendo utilizada por outro processo
        try(ServerSocket serverSocket = new ServerSocket(porta)){

            System.out.println("aguardando por conexões...");

            // enquanto a thread atual não for interrompida com CTRL C
            while(!Thread.currentThread().isInterrupted()) {
                Socket clientSocket = serverSocket.accept(); // socket do cliente. Esperando IO

                // invoca o método run da classe AtenderClient. Start cria uma thread
                Thread.ofVirtual().start(new AtenderCliente(clientSocket));
            }

        } catch(Exception e){
            System.err.println("Erro: " + e);
        }

        //serverSocket.close(); // libera recurso de IO

    }
}
